server:
  port: 83
spring:
  application:
    name: nacos-payment-consumenrs
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#服务提供者的地址
service-url:
  nacos-priovider-servic: http://nacos-payment-provider