server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/ #集群版
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
logging:
  level:
    com.shiwen.config.OpenFeignConfig: debug
feign:
  hystrix:
    enabled: true

