server:
  port: 80
spring:
  application:
    name: server-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
        service-name: ${spring.application.name}